# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %%
import os
import pandas as pd
import re
import random
from decimal import Decimal, ROUND_HALF_UP
from itertools import combinations
import tqdm
import sys

# Automatically set working directory to project root
if os.getcwd().endswith('src/synthetic_cot'):
    os.chdir('../../')
if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())
print(f"Current working directory: {os.getcwd()}")

from src.synthetic_cot.baseline_generators import SOLVER_MAP as BASELINE_MAP, classify_puzzle
from src.synthetic_cot.true_solvers import TRUE_SOLVER_MAP
from src.synthetic_cot.donald_solvers import DONALD_SOLVER_MAP

def is_correct(pred, truth):
    if pred is None:
        return False
    pred_s = str(pred).strip()
    truth_s = str(truth).strip()
    if pred_s == truth_s:
        return True
    try:
        return abs(float(pred_s) - float(truth_s)) <= 1e-2
    except (ValueError, TypeError):
        return False

# %%
df = pd.read_csv('data/train.csv')
print(f"Loaded {len(df)} rows from train.csv")

# Use a representative sample for faster evaluation if needed, or full
subset = df # .sample(1000, random_state=42)
subset = df.sample(300, random_state=42)

results = []
sample_data = {}
incorrect_data = {}

for _, row in tqdm.tqdm(subset.iterrows(), total=len(subset)):
    p = row['prompt']
    a = str(row['answer'])
    cat = classify_puzzle(p)
    
    # Run Baseline (Peeks at Answer)
    b_solved = False
    b_cot = None
    if cat in BASELINE_MAP:
        b_pred, b_cot = BASELINE_MAP[cat](p, a)
        if is_correct(b_pred, a) or (b_cot and f"\\boxed{{{a}}}" in b_cot):
            b_solved = True
            
    # Run True Solver (Doesn't Peek)
    t_solved = False
    t_cot = None
    if cat in TRUE_SOLVER_MAP:
        t_pred, t_cot = TRUE_SOLVER_MAP[cat](p)
        if is_correct(t_pred, a):
            t_solved = True
            
    # Run Donald Solver (Strict Formatting, Doesn't Peek)
    d_solved = False
    d_cot = None
    d_pred = None
    if cat in DONALD_SOLVER_MAP:
        d_pred, d_cot = DONALD_SOLVER_MAP[cat](p)
        if is_correct(d_pred, a):
            d_solved = True
        else:
            if cat not in incorrect_data:
                incorrect_data[cat] = []
            if len(incorrect_data[cat]) < 3:
                incorrect_data[cat].append({
                    'prompt': p,
                    'answer': a,
                    'predicted': d_pred,
                    'cot': d_cot
                })
    
    results.append({
        'id': row['id'],
        'category': cat,
        'baseline_solved': b_solved,
        'true_solved': t_solved,
        'donald_solved': d_solved
    })
    
    if (b_solved or t_solved or d_solved) and cat not in sample_data:
        sample_data[cat] = {
            'prompt': p,
            'answer': a,
            'baseline_cot': b_cot,
            'true_cot': t_cot,
            'donald_cot': d_cot
        }

results_df = pd.DataFrame(results)

# %% [markdown]
# # Statistics Comparison

# %%
stats = results_df.groupby('category').agg(
    total=('id', 'count'),
    baseline_solved=('baseline_solved', 'sum'),
    true_solved=('true_solved', 'sum'),
    donald_solved=('donald_solved', 'sum')
)
stats['baseline_acc'] = (stats['baseline_solved'] / stats['total'] * 100).round(2)
stats['true_acc'] = (stats['true_solved'] / stats['total'] * 100).round(2)
stats['donald_acc'] = (stats['donald_solved'] / stats['total'] * 100).round(2)
print(stats[['total', 'baseline_acc', 'true_acc', 'donald_acc']])

# %% [markdown]
# # Sample Inspection (Donald Solvers Only)

# %%
for cat, data in sample_data.items():
    if not data['donald_cot']: # Skip if no CoT generated by donald solver
        continue
        
    print("=" * 80)
    print(f"CATEGORY: {cat}")
    print("=" * 80)
    print(f"PROMPT:\n{data['prompt']}")
    print("-" * 40)
    print(f"EXPECTED ANSWER: {data['answer']}")
    print("-" * 40)
    print(f"DONALD SOLVER COT:\n{data['donald_cot']}")
    print("\n")

# %% [markdown]
# # Incorrect Sample Inspection (Donald Solvers Only)

# %%
for cat, samples in incorrect_data.items():
    print("#" * 80)
    print(f" INCORRECT EXAMPLES: {cat}")
    print("#" * 80)
    for i, data in enumerate(samples):
        print(f"\n--- Example {i+1} ---")
        print(f"PROMPT: {data['prompt'][:200]}...")
        print(f"EXPECTED: {data['answer']}")
        print(f"PREDICTED: {data['predicted']}")
        print("-" * 20)
        print(f"COT (TRUNCATED):\n{data['cot']}")
        print("\n")
# %%
